name: Bug Bot - Automated Bug Detection

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on code file changes
    # paths:
    #   - "**/*.py"
    #   - "**/*.js"
    #   - "**/*.ts"
    #   - "**/*.tsx"
    #   - "**/*.jsx"

jobs:
  bug-detection:
    # Optional: Filter by PR size or author
    # if: |
    #   github.event.pull_request.additions + github.event.pull_request.deletions > 50
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Bug Bot Analysis
        id: bug-bot
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            # Bug Bot - Critical Runtime Bug Detection
            
            You are Bug Bot, a specialized analyzer focused EXCLUSIVELY on critical runtime bugs that will cause crashes, data corruption, or security vulnerabilities in production.
            
            ## ONLY Flag These Critical Issues:
            
            ### **Runtime Crash Bugs (CRITICAL)**:
            - Division by zero (guaranteed crash)
            - Null pointer dereferences (crash)
            - Array index out of bounds (crash)
            - Unhandled exceptions that propagate to top level
            - Type conversion errors on external input (e.g., `int()` without try-catch)
            - Missing await on required async operations causing deadlock
            - Stack overflow from infinite recursion
            
            ### **Data Corruption Bugs (CRITICAL)**:
            - Race conditions in shared state modification
            - Incorrect bounds checking leading to buffer overflows
            - State mutations that break immutability contracts
            - Off-by-one errors in critical calculations
            - Incorrect async/sync patterns causing data inconsistency
            
            ### **Resource Leak Bugs (CRITICAL)**:
            - Database connections not closed in error paths
            - File handles leaked in exception scenarios
            - Memory leaks from circular references
            - Async context managers not properly cleaned up
            
            ### **Security Vulnerabilities (CRITICAL)**:
            - SQL injection from unsanitized input
            - Command injection risks
            - Path traversal vulnerabilities
            - Hardcoded secrets or credentials
            - XSS from unescaped user input
            
            ## **DO NOT Flag These**:
            - Style issues, formatting, naming conventions
            - Performance optimizations or suggestions
            - Missing error logging or warnings
            - Code organization or architecture suggestions
            - Best practices that don't cause runtime failures
            - Potential edge cases that are unlikely or handled elsewhere
            - Missing documentation or comments
            - Timeout configurations unless guaranteed to cause deadlock
            
            ## Review Criteria:
            
            **Only report bugs that meet ALL criteria:**
            1. ✅ **Will definitely cause a runtime error/crash in realistic usage**
            2. ✅ **Cannot be caught by normal testing (edge cases, external input, race conditions)**
            3. ✅ **Has clear, direct impact on production stability**
            4. ✅ **Fix is specific and actionable**
            
            ## Output Format:
            
            ### 🚨 Critical Bug Report
            
            **Summary**: Found X critical runtime bugs that require immediate fixes.
            
            #### Critical Bugs (Must Fix Before Merge):
            
            For each bug:
            **1. [Bug Type] - [Location]**
            - **Issue**: [Specific problem that will cause runtime failure]
            - **Impact**: [Exact failure mode - crash, data corruption, etc.]
            - **Fix**: [Specific code change needed]
            
            If no critical bugs: "✅ No critical runtime bugs detected"
            
            ## Instructions:
            - Be extremely selective - only flag bugs that WILL cause production failures
            - Provide exact line numbers and specific failure scenarios
            - Focus on external input handling, async patterns, and resource management
            - Ignore anything that's not a guaranteed runtime problem
            
            Use `gh pr comment` with your Bash tool to post the bug detection report as a comment on the PR.
          
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'